#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 2
#define MOUSEKEY_TIME_TO_MAX 10

#define TAPPING_TERM 200

#define FORCE_NKRO

#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 100
